# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License
version: '3.3'
services:
  zookeeper:
    image: zookeeper:3.4.10
    restart: always
    hostname: zookeeper
    networks:
      - logsearch-network
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
  solr:
    image: apache/ambari-infra-solr:latest
    restart: always
    hostname: solr
    container_name: infra_solr
    ports:
      - "8886:8886"
    networks:
      - logsearch-network
    environment:
      ZK_CONNECT_STRING: zookeeper:2181
      SOLR_PORT: 8886
      SOLR_OPTS: "-Dsolr.hdfs.home={TEST_SOLR_CLOUD_STORAGE_URL} -Dsolr.hdfs.confdir=/etc/hadoop/conf"
      CLOUD_MODE: "true"
    volumes:
      - ./core-site.xml:/etc/hadoop/conf/core-site.xml
  logsearch:
    image: apache/ambari-logsearch-portal:latest
    restart: always
    labels:
      logfeeder.log.type: "logsearch_server"
    hostname: logsearch.apache.org
    networks:
      - logsearch-network
    ports:
      - 61888:61888
      - 4444:4444
      - 5005:5005
    environment:
      ZK_CONNECT_STRING: zookeeper:2181/infra-solr
    volumes:
      - ./cloud-storage-solrconfig.xml:/usr/lib/ambari-logsearch-portal/conf/solr_configsets/hadoop_logs/conf/solrconfig.xml
  fakes3:
    image: localstack/localstack
    hostname: fakes3
    ports:
      - "4569:4569"
    environment:
      - SERVICES=s3:4569
      - DEBUG=s3
    networks:
      logsearch-network:
        aliases:
          - testbucket.fakes3
  fakegcs:
    image: singularities/datastore-emulator
    hostname: fakegcs
    ports:
      - "8081:8081"
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    networks:
      - logsearch-network
  fakeazure:
    image: arafato/azurite
    hostname: fakeazure
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - logsearch-network
networks:
   logsearch-network:
      driver: bridge
